#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libspiro
Version  : 0.5.20150702
Release  : 1
URL      : https://github.com/fontforge/libspiro/archive/0.5.20150702.tar.gz
Source0  : https://github.com/fontforge/libspiro/archive/0.5.20150702.tar.gz
Summary  : A library for curve design. Clothoid to bezier conversion. A mechanism for drawing smooth contours with constant curvature at the spline joins.
Group    : Development/Tools
License  : GPL-3.0
Requires: libspiro-lib
Requires: libspiro-license
BuildRequires : sed

%description
LibSpiro is a shared library designed to give programs the ability to create
smooth continuous curves based on a given set of codes and X,Y constraints.

%package dev
Summary: dev components for the libspiro package.
Group: Development
Requires: libspiro-lib = %{version}-%{release}
Provides: libspiro-devel = %{version}-%{release}

%description dev
dev components for the libspiro package.


%package lib
Summary: lib components for the libspiro package.
Group: Libraries
Requires: libspiro-license = %{version}-%{release}

%description lib
lib components for the libspiro package.


%package license
Summary: license components for the libspiro package.
Group: Default

%description license
license components for the libspiro package.


%prep
%setup -q -n libspiro-0.5.20150702

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1537296390
%reconfigure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1537296390
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/libspiro
cp COPYING %{buildroot}/usr/share/doc/libspiro/COPYING
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib64/libspiro.so
/usr/lib64/pkgconfig/libspiro.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libspiro.so.0
/usr/lib64/libspiro.so.0.0.5

%files license
%defattr(-,root,root,-)
/usr/share/doc/libspiro/COPYING
